//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Prog_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public int Id { get; set; }
        public string identificacion { get; set; }
        public string contrasenia { get; set; }
    }
}
